name: quadroflow_core
description: A visual organization application that combines the simplicity of the Kanban board with the fluidity of an agile workflow.

homepage: https://softyes.com.br
repository: https://github.com/QuadroFlow/quadroflow_core

version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  vaden_core: ^0.0.3
  dart_mappable: ^4.6.0

dev_dependencies:
  test: ^1.25.6
  build_runner: ^2.7.0
  very_good_analysis: ^9.0.0
  dart_mappable_builder: ^4.5.0
